auth: null

admin:
  socketPath: "/run/hummingbird/S.hummingbird-admin"

transports:
  - type: socket
    bindAddress: 0.0.0.0
    bindPort: 1883
    listenBacklog: 32
    connectionLimit: 1024
  - type: websocket
    transport:
      type: socket
      bindAddress: 0.0.0.0
      bindPort: 1884
      listenBacklog: 5
#  - type: tls
#    transport:
#      type: socket
#      bindAddress: 0.0.0.0
#      bindPort: 8883
#      listenBacklog: 5
#    wantClientCert: true
#    crtFilePath: /etc/hummingbird/secrets/cert.crt
#    keyFilePath: /etc/hummingbird/secrets/cert.key

prometheus:
  bindAddress: "*"
  bindPort: 9001

logging:
  level: INFO
  appenders:
    - type: console

