resolver: lts-16.3
packages:
 - "."
 - "bounce"
extra-deps:
  - socket-0.8.3.0
  - socket-unix-0.2.0.0
  - prometheus-metrics-ghc-1.0.1
  - wai-middleware-prometheus-1.0.0
  - net-mqtt-0.7.0.1
  - stm-containers-1.1.0.4
  - stm-hamt-1.2.0.4
  - primitive-extras-0.8
  - primitive-unlifted-0.1.3.0
  - git: https://github.com/AeroStun/haskell-mqtt.git
    commit: 6aec6e55a1f9e3c6ea23683f578721a6ccf1a555
  - git: https://github.com/lpeterse/haskell-networking.git
    commit: b79d22a2b95c6ba4bb16b5b47bfb0ea06df9ddbd
flags: {}
extra-package-dbs: []
